import type { MatchResponse } from './types'

export const DEMO_DATA: MatchResponse = {
  total_trials_fetched: 200,
  total_trials_scored: 47,
  patient_lat: 40.7484,
  patient_lon: -73.9967,
  matches: [
    {
      nct_id: 'NCT05119062',
      brief_title: 'Trastuzumab Deruxtecan vs. Trastuzumab Emtansine in HER2-Positive Metastatic Breast Cancer (DESTINY-Breast03)',
      final_score: 0.87,
      headline: 'Strong match — HER2+ profile aligns with all primary eligibility criteria',
      summary: 'Randomised Phase 3 trial comparing T-DXd (trastuzumab deruxtecan) against T-DM1 in patients with HER2-positive unresectable or metastatic breast cancer who received prior trastuzumab and a taxane. Primary endpoint is progression-free survival by blinded independent central review.',
      why_eligible: [
        'HER2+ biomarker status confirmed — matches the primary eligibility requirement',
        'Age 52 falls within the eligible range (18–75)',
        'Prior trastuzumab satisfies the required prior HER2-directed therapy',
        'ECOG PS 1 is within the allowed range (0–1)',
      ],
      why_uncertain: [
        'Prior radiation therapy — some sites require a washout period; site-specific clarification needed',
        'Hypertension — cardiac monitoring protocol may apply; not an automatic exclusion',
      ],
      why_excluded: [],
      score_breakdown: { semantic: 0.91, eligibility: 0.88, geo: 0.78, final: 0.87 },
      distance_miles: 3.2,
      hard_excluded: false,
      llm_narrative: 'This patient is an excellent candidate for DESTINY-Breast03. The HER2+ status, prior trastuzumab treatment, and ECOG PS 1 all align well with the core eligibility criteria. The prior radiation warrants a quick clarification with the site coordinator but is unlikely to be disqualifying.',
      overall_status: 'RECRUITING',
      phases: ['PHASE3'],
      conditions: ['HER2-Positive Breast Neoplasms'],
      locations_count: 12,
      countries_at_sites: ['United States', 'United Kingdom', 'Germany', 'France', 'Japan'],
    },
    {
      nct_id: 'NCT04523974',
      brief_title: 'Tucatinib Plus Trastuzumab and Capecitabine for HER2+ Metastatic Breast Cancer With Brain Metastases (HER2CLIMB-02)',
      final_score: 0.74,
      headline: 'Good match — HER2+ targeting aligns; CNS involvement status should be confirmed',
      summary: 'Phase 2 study evaluating the triplet combination of tucatinib, trastuzumab, and capecitabine in HER2-positive metastatic breast cancer with active or stable brain metastases. Notably enrolls patients with previously excluded CNS involvement.',
      why_eligible: [
        'HER2+ confirmed — tucatinib is a HER2-selective TKI designed for this subtype',
        'Prior trastuzumab satisfies required prior HER2-directed therapy',
        'Age and ECOG PS are within protocol bounds',
      ],
      why_uncertain: [
        'Brain metastases status not specified in profile — this trial specifically targets patients with CNS involvement',
        'Capecitabine tolerability not assessed; prior fluoropyrimidine exposure should be checked',
      ],
      why_excluded: [],
      score_breakdown: { semantic: 0.79, eligibility: 0.72, geo: 0.62, final: 0.74 },
      distance_miles: 18.5,
      hard_excluded: false,
      llm_narrative: null,
      overall_status: 'RECRUITING',
      phases: ['PHASE2'],
      conditions: ['HER2-Positive Breast Neoplasms', 'Brain Metastases'],
      locations_count: 6,
      countries_at_sites: ['United States', 'Canada', 'Australia'],
    },
    {
      nct_id: 'NCT03424005',
      brief_title: 'Neratinib Monotherapy in HER2-Mutated Solid Tumors (SUMMIT Basket Trial)',
      final_score: 0.54,
      headline: 'Moderate match — HER2 mutation vs. amplification distinction must be confirmed',
      summary: 'Open-label Phase 2 basket trial of neratinib (pan-HER TKI) in patients with HER2-activating mutations across multiple solid tumour types including breast cancer. Requires documented HER2-activating mutation, distinct from HER2 amplification alone.',
      why_eligible: [
        'HER2+ status may satisfy eligibility if an activating mutation is documented',
        'Age and performance status meet inclusion thresholds',
        'Multi-tumour basket design accepts breast cancer as an enrolled cohort',
      ],
      why_uncertain: [
        'Trial requires a HER2-activating mutation (e.g. L755S, V842I), not just amplification — genomic sequencing required',
        'Prior pan-HER TKI use is exclusionary; profile does not clarify this history',
      ],
      why_excluded: [],
      score_breakdown: { semantic: 0.61, eligibility: 0.48, geo: 0.44, final: 0.54 },
      distance_miles: 42.1,
      hard_excluded: false,
      llm_narrative: null,
      overall_status: 'RECRUITING',
      phases: ['PHASE2'],
      conditions: ['Breast Neoplasms', 'HER2-Mutated Solid Tumors'],
      locations_count: 23,
      countries_at_sites: ['United States', 'United Kingdom', 'Germany', 'Netherlands', 'Spain', 'South Korea'],
    },
    {
      nct_id: 'NCT04710225',
      brief_title: 'Pembrolizumab Plus Chemotherapy for Early-Stage Triple-Negative Breast Cancer (KEYNOTE-522)',
      final_score: 0.09,
      headline: 'Excluded — TNBC phenotype required; patient is HER2+',
      summary: 'Phase 3 study of pembrolizumab plus chemotherapy as neoadjuvant treatment followed by adjuvant pembrolizumab for early-stage triple-negative (ER−, PR−, HER2−) breast cancer.',
      why_eligible: [],
      why_uncertain: [],
      why_excluded: [
        'Hard exclusion: trial requires triple-negative status (ER−, PR−, HER2−) — patient is HER2+, disqualifying from this protocol',
      ],
      score_breakdown: { semantic: 0.32, eligibility: 0.02, geo: 0.61, final: 0.09 },
      distance_miles: 2.8,
      hard_excluded: true,
      llm_narrative: null,
      overall_status: 'RECRUITING',
      phases: ['PHASE3'],
      conditions: ['Triple Negative Breast Neoplasms'],
      locations_count: 8,
      countries_at_sites: ['United States', 'Canada'],
    },
  ],
}
