import type { MatchResponse, ResearcherSearchResponse } from './types'

export const DEMO_DATA: MatchResponse = {
  total_trials_fetched: 200,
  total_trials_scored: 47,
  patient_lat: 40.7484,
  patient_lon: -73.9967,
  matches: [
    {
      nct_id: 'NCT05119062',
      brief_title: 'Trastuzumab Deruxtecan vs. Trastuzumab Emtansine in HER2-Positive Metastatic Breast Cancer (DESTINY-Breast03)',
      final_score: 0.87,
      headline: 'Strong match — HER2+ profile aligns with all primary eligibility criteria',
      summary: 'Randomised Phase 3 trial comparing T-DXd (trastuzumab deruxtecan) against T-DM1 in patients with HER2-positive unresectable or metastatic breast cancer who received prior trastuzumab and a taxane. Primary endpoint is progression-free survival by blinded independent central review.',
      why_eligible: [
        'HER2+ biomarker status confirmed — matches the primary eligibility requirement',
        'Age 52 falls within the eligible range (18–75)',
        'Prior trastuzumab satisfies the required prior HER2-directed therapy',
        'ECOG PS 1 is within the allowed range (0–1)',
      ],
      why_uncertain: [
        'Prior radiation therapy — some sites require a washout period; site-specific clarification needed',
        'Hypertension — cardiac monitoring protocol may apply; not an automatic exclusion',
      ],
      why_excluded: [],
      score_breakdown: { semantic: 0.91, eligibility: 0.88, geo: 0.78, final: 0.87 },
      distance_miles: 3.2,
      hard_excluded: false,
      llm_narrative: 'This patient is an excellent candidate for DESTINY-Breast03. The HER2+ status, prior trastuzumab treatment, and ECOG PS 1 all align well with the core eligibility criteria. The prior radiation warrants a quick clarification with the site coordinator but is unlikely to be disqualifying.',
      overall_status: 'ACTIVE_NOT_RECRUITING',
      phases: ['PHASE3'],
      conditions: ['HER2-Positive Breast Neoplasms'],
      locations_count: 12,
      countries_at_sites: ['United States', 'United Kingdom', 'Germany', 'France', 'Japan'],
      minimum_age: '18 Years',
      maximum_age: '75 Years',
      start_date: '2021-06-01',
      primary_completion_date: '2024-12-01',
    },
    {
      nct_id: 'NCT04523974',
      brief_title: 'Tucatinib Plus Trastuzumab and Capecitabine for HER2+ Metastatic Breast Cancer With Brain Metastases (HER2CLIMB-02)',
      final_score: 0.74,
      headline: 'Good match — HER2+ targeting aligns; CNS involvement status should be confirmed',
      summary: 'Phase 2 study evaluating the triplet combination of tucatinib, trastuzumab, and capecitabine in HER2-positive metastatic breast cancer with active or stable brain metastases. Notably enrolls patients with previously excluded CNS involvement.',
      why_eligible: [
        'HER2+ confirmed — tucatinib is a HER2-selective TKI designed for this subtype',
        'Prior trastuzumab satisfies required prior HER2-directed therapy',
        'Age and ECOG PS are within protocol bounds',
      ],
      why_uncertain: [
        'Brain metastases status not specified in profile — this trial specifically targets patients with CNS involvement',
        'Capecitabine tolerability not assessed; prior fluoropyrimidine exposure should be checked',
      ],
      why_excluded: [],
      score_breakdown: { semantic: 0.79, eligibility: 0.72, geo: 0.62, final: 0.74 },
      distance_miles: 18.5,
      hard_excluded: false,
      llm_narrative: null,
      overall_status: 'UNKNOWN',
      phases: ['PHASE2'],
      conditions: ['HER2-Positive Breast Neoplasms', 'Brain Metastases'],
      locations_count: 6,
      countries_at_sites: ['United States', 'Canada', 'Australia'],
      minimum_age: '18 Years',
      maximum_age: null,
      start_date: '2020-09-01',
      primary_completion_date: null,
    },
    {
      nct_id: 'NCT03424005',
      brief_title: 'Neratinib Monotherapy in HER2-Mutated Solid Tumors (SUMMIT Basket Trial)',
      final_score: 0.54,
      headline: 'Moderate match — HER2 mutation vs. amplification distinction must be confirmed',
      summary: 'Open-label Phase 2 basket trial of neratinib (pan-HER TKI) in patients with HER2-activating mutations across multiple solid tumour types including breast cancer. Requires documented HER2-activating mutation, distinct from HER2 amplification alone.',
      why_eligible: [
        'HER2+ status may satisfy eligibility if an activating mutation is documented',
        'Age and performance status meet inclusion thresholds',
        'Multi-tumour basket design accepts breast cancer as an enrolled cohort',
      ],
      why_uncertain: [
        'Trial requires a HER2-activating mutation (e.g. L755S, V842I), not just amplification — genomic sequencing required',
        'Prior pan-HER TKI use is exclusionary; profile does not clarify this history',
      ],
      why_excluded: [],
      score_breakdown: { semantic: 0.61, eligibility: 0.48, geo: 0.44, final: 0.54 },
      distance_miles: 42.1,
      hard_excluded: false,
      llm_narrative: null,
      overall_status: 'RECRUITING',
      phases: ['PHASE2'],
      conditions: ['Breast Neoplasms', 'HER2-Mutated Solid Tumors'],
      locations_count: 23,
      countries_at_sites: ['United States', 'United Kingdom', 'Germany', 'Netherlands', 'Spain', 'South Korea'],
      minimum_age: '18 Years',
      maximum_age: '70 Years',
      start_date: '2018-03-01',
      primary_completion_date: '2023-06-01',
    },
    {
      nct_id: 'NCT04710225',
      brief_title: 'Pembrolizumab Plus Chemotherapy for Early-Stage Triple-Negative Breast Cancer (KEYNOTE-522)',
      final_score: 0.09,
      headline: 'Excluded — TNBC phenotype required; patient is HER2+',
      summary: 'Phase 3 study of pembrolizumab plus chemotherapy as neoadjuvant treatment followed by adjuvant pembrolizumab for early-stage triple-negative (ER−, PR−, HER2−) breast cancer.',
      why_eligible: [],
      why_uncertain: [],
      why_excluded: [
        'Hard exclusion: trial requires triple-negative status (ER−, PR−, HER2−) — patient is HER2+, disqualifying from this protocol',
      ],
      score_breakdown: { semantic: 0.32, eligibility: 0.02, geo: 0.61, final: 0.09 },
      distance_miles: 2.8,
      hard_excluded: true,
      llm_narrative: null,
      overall_status: 'COMPLETED',
      phases: ['PHASE3'],
      conditions: ['Triple Negative Breast Neoplasms'],
      locations_count: 8,
      countries_at_sites: ['United States', 'Canada'],
      minimum_age: '18 Years',
      maximum_age: '65 Years',
      start_date: '2021-01-01',
      primary_completion_date: '2023-03-01',
    },
  ],
}

export const RESEARCHER_DEMO_DATA: ResearcherSearchResponse = {
  total_fetched: 312,
  patient_lat: 40.7128,
  patient_lon: -74.006,
  geo_warning: null,
  results: [
    {
      nct_id: 'NCT05312619',
      brief_title: 'Daratumumab, Bortezomib, Lenalidomide and Dexamethasone (Dara-VRd) in Newly Diagnosed Multiple Myeloma',
      overall_status: 'RECRUITING',
      phases: ['PHASE3'],
      conditions: ['Multiple Myeloma', 'Newly Diagnosed Multiple Myeloma'],
      brief_summary: 'A randomized Phase 3 study comparing daratumumab plus bortezomib, lenalidomide, and dexamethasone (Dara-VRd) versus VRd alone as induction therapy in patients with newly diagnosed multiple myeloma eligible for autologous stem cell transplant. Primary endpoint is progression-free survival assessed by blinded central review.',
      start_date: '2022-04-01',
      primary_completion_date: '2027-06-01',
      healthy_volunteers: false,
      minimum_age: '18 Years',
      maximum_age: '70 Years',
      nearest_facility: 'Memorial Sloan Kettering Cancer Center',
      nearest_city: 'New York',
      nearest_state: 'New York',
      nearest_country: 'United States',
      nearest_distance_miles: 4.2,
      nearest_lat: 40.7644,
      nearest_lon: -73.9572,
      investigators: [
        { name: 'Sham Mailankody, M.D.', role: 'PRINCIPAL_INVESTIGATOR', email: 's-mailankody@mskcc.org', phone: '212-639-7455' },
        { name: 'Hani Hassoun, M.D.', role: 'SUB_INVESTIGATOR', email: 'hassounh@mskcc.org', phone: null },
      ],
      site_contacts: [
        { name: 'Clinical Trials Office', role: 'CONTACT', email: 'clinicaltrials@mskcc.org', phone: '212-639-7202' },
      ],
      overall_contacts: [],
      total_sites: 48,
      countries_at_sites: ['United States', 'Canada', 'United Kingdom', 'Germany', 'France'],
      sponsor_type: 'INDUSTRY',
      study_type: 'INTERVENTIONAL',
      intervention_types: ['DRUG', 'BIOLOGICAL'],
    },
    {
      nct_id: 'NCT05552612',
      brief_title: 'BCMA-Directed CAR-T Cell Therapy (bb2121) in Relapsed/Refractory Multiple Myeloma — Long-Term Follow-Up',
      overall_status: 'RECRUITING',
      phases: ['PHASE2'],
      conditions: ['Relapsed/Refractory Multiple Myeloma'],
      brief_summary: 'An open-label Phase 2 study evaluating the long-term safety and efficacy of idecabtagene vicleucel (bb2121), a BCMA-directed chimeric antigen receptor T-cell therapy, in adult patients with relapsed or refractory multiple myeloma who received at least three prior lines of therapy including a proteasome inhibitor and an immunomodulatory agent.',
      start_date: '2022-09-15',
      primary_completion_date: '2026-12-01',
      healthy_volunteers: false,
      minimum_age: '18 Years',
      maximum_age: null,
      nearest_facility: 'Dana-Farber Cancer Institute',
      nearest_city: 'Boston',
      nearest_state: 'Massachusetts',
      nearest_country: 'United States',
      nearest_distance_miles: 215.3,
      nearest_lat: 42.3372,
      nearest_lon: -71.1069,
      investigators: [
        { name: 'Paul Richardson, M.D.', role: 'PRINCIPAL_INVESTIGATOR', email: 'paul_richardson@dfci.harvard.edu', phone: '617-632-2104' },
        { name: 'Nikhil Munshi, M.D.', role: 'SUB_INVESTIGATOR', email: 'nikhil_munshi@dfci.harvard.edu', phone: null },
      ],
      site_contacts: [],
      overall_contacts: [
        { name: 'Research Intake', role: 'CONTACT', email: 'clinical-trials@dfci.harvard.edu', phone: '877-338-7425' },
      ],
      total_sites: 22,
      countries_at_sites: ['United States', 'United Kingdom', 'Netherlands', 'Spain'],
      sponsor_type: 'INDUSTRY',
      study_type: 'INTERVENTIONAL',
      intervention_types: ['BIOLOGICAL'],
    },
    {
      nct_id: 'NCT05029414',
      brief_title: 'Isatuximab Plus Carfilzomib and Dexamethasone in High-Risk Relapsed Multiple Myeloma (IKEMA-2)',
      overall_status: 'RECRUITING',
      phases: ['PHASE2'],
      conditions: ['Multiple Myeloma', 'High-Risk Relapsed Multiple Myeloma'],
      brief_summary: 'A multicenter, randomized Phase 2 study of isatuximab in combination with carfilzomib and dexamethasone (Isa-Kd) versus Kd alone in patients with high-risk relapsed multiple myeloma, defined by del(17p), t(4;14), t(14;16), or gain(1q21). The primary endpoint is overall response rate; secondary endpoints include MRD negativity rate and PFS.',
      start_date: '2021-11-01',
      primary_completion_date: '2026-03-01',
      healthy_volunteers: false,
      minimum_age: '18 Years',
      maximum_age: null,
      nearest_facility: 'University of Pennsylvania Abramson Cancer Center',
      nearest_city: 'Philadelphia',
      nearest_state: 'Pennsylvania',
      nearest_country: 'United States',
      nearest_distance_miles: 94.6,
      nearest_lat: 39.9496,
      nearest_lon: -75.1948,
      investigators: [
        { name: 'Alfred Garfall, M.D.', role: 'PRINCIPAL_INVESTIGATOR', email: 'alfred.garfall@pennmedicine.upenn.edu', phone: '215-615-5858' },
      ],
      site_contacts: [
        { name: 'Abramson Clinical Trials', role: 'CONTACT', email: 'PennCancerTrials@pennmedicine.upenn.edu', phone: '855-216-0098' },
      ],
      overall_contacts: [],
      total_sites: 31,
      countries_at_sites: ['United States', 'United Kingdom', 'Germany', 'Australia', 'South Korea'],
      sponsor_type: 'INDUSTRY',
      study_type: 'INTERVENTIONAL',
      intervention_types: ['DRUG', 'BIOLOGICAL'],
    },
    {
      nct_id: 'NCT04083898',
      brief_title: 'Teclistamab (JNJ-64007957) Bispecific Antibody in Relapsed or Refractory Multiple Myeloma',
      overall_status: 'RECRUITING',
      phases: ['PHASE1', 'PHASE2'],
      conditions: ['Multiple Myeloma', 'Relapsed or Refractory Multiple Myeloma'],
      brief_summary: 'MajesTEC-1 is a Phase 1/2, open-label, multicenter study of teclistamab, a BCMA × CD3 bispecific antibody, in patients with relapsed or refractory multiple myeloma. The study evaluates subcutaneous teclistamab monotherapy and in combination with other agents. Investigator sites are actively enrolling into expansion cohorts.',
      start_date: '2019-11-15',
      primary_completion_date: '2025-12-01',
      healthy_volunteers: false,
      minimum_age: '18 Years',
      maximum_age: null,
      nearest_facility: 'Winship Cancer Institute of Emory University',
      nearest_city: 'Atlanta',
      nearest_state: 'Georgia',
      nearest_country: 'United States',
      nearest_distance_miles: 862.4,
      nearest_lat: 33.7957,
      nearest_lon: -84.3238,
      investigators: [
        { name: 'Jonathan Kaufman, M.D.', role: 'PRINCIPAL_INVESTIGATOR', email: 'jonathan.kaufman@emory.edu', phone: '404-778-1900' },
      ],
      site_contacts: [
        { name: 'Winship Research Recruitment', role: 'CONTACT', email: 'WinshipResearch@emory.edu', phone: '888-946-7447' },
      ],
      overall_contacts: [],
      total_sites: 65,
      countries_at_sites: ['United States', 'United Kingdom', 'France', 'Germany', 'Spain', 'Italy', 'Japan'],
      sponsor_type: 'INDUSTRY',
      study_type: 'INTERVENTIONAL',
      intervention_types: ['BIOLOGICAL'],
    },
    {
      nct_id: 'NCT03989414',
      brief_title: 'Autologous Stem Cell Transplant Timing and Maintenance in Standard-Risk Multiple Myeloma (DETERMINATION)',
      overall_status: 'RECRUITING',
      phases: ['PHASE3'],
      conditions: ['Multiple Myeloma', 'Standard-Risk Multiple Myeloma'],
      brief_summary: 'A randomized Phase 3 NIH-sponsored trial comparing early versus delayed autologous stem cell transplantation in standard-risk, newly diagnosed multiple myeloma. Patients in both arms receive lenalidomide, bortezomib, and dexamethasone induction followed by lenalidomide maintenance. The study addresses optimal transplant timing to maximize quality-adjusted survival.',
      start_date: '2020-03-01',
      primary_completion_date: '2028-06-01',
      healthy_volunteers: false,
      minimum_age: '18 Years',
      maximum_age: '65 Years',
      nearest_facility: 'Northwestern University Robert H. Lurie Comprehensive Cancer Center',
      nearest_city: 'Chicago',
      nearest_state: 'Illinois',
      nearest_country: 'United States',
      nearest_distance_miles: 790.1,
      nearest_lat: 41.9003,
      nearest_lon: -87.6219,
      investigators: [
        { name: 'Jason Westin, M.D.', role: 'PRINCIPAL_INVESTIGATOR', email: 'jwestin@nm.org', phone: '312-695-0990' },
        { name: 'Shira Dinner, M.D.', role: 'SUB_INVESTIGATOR', email: null, phone: null },
      ],
      site_contacts: [
        { name: 'Cancer Trials Office', role: 'CONTACT', email: 'cancertrials@nm.org', phone: '312-695-1301' },
      ],
      overall_contacts: [],
      total_sites: 89,
      countries_at_sites: ['United States'],
      sponsor_type: 'NIH',
      study_type: 'INTERVENTIONAL',
      intervention_types: ['DRUG', 'PROCEDURE'],
    },
    {
      nct_id: 'NCT05028348',
      brief_title: 'Selinexor, Bortezomib, and Dexamethasone (XVd) vs. Bortezomib and Dexamethasone in Previously Treated Myeloma',
      overall_status: 'RECRUITING',
      phases: ['PHASE3'],
      conditions: ['Multiple Myeloma', 'Previously Treated Multiple Myeloma'],
      brief_summary: 'STOMP is a randomized, double-blind Phase 3 study comparing selinexor, bortezomib, and dexamethasone (XVd) to placebo, bortezomib, and dexamethasone (Vd) in patients with multiple myeloma who have received 1–3 prior lines of therapy. Selinexor is a first-in-class selective inhibitor of nuclear export (SINE) compound targeting XPO1.',
      start_date: '2021-07-01',
      primary_completion_date: '2026-09-01',
      healthy_volunteers: false,
      minimum_age: '18 Years',
      maximum_age: null,
      nearest_facility: 'Princess Margaret Cancer Centre',
      nearest_city: 'Toronto',
      nearest_state: 'Ontario',
      nearest_country: 'Canada',
      nearest_distance_miles: 387.2,
      nearest_lat: 43.6567,
      nearest_lon: -79.3907,
      investigators: [
        { name: 'Donna Reece, M.D.', role: 'PRINCIPAL_INVESTIGATOR', email: 'donna.reece@uhn.ca', phone: '416-946-4501' },
      ],
      site_contacts: [
        { name: 'Celeste Yu, MSc', role: 'CONTACT', email: 'Celeste.Yu@uhn.ca', phone: '416-946-4501' },
      ],
      overall_contacts: [],
      total_sites: 41,
      countries_at_sites: ['Canada', 'United States', 'United Kingdom', 'Australia'],
      sponsor_type: 'INDUSTRY',
      study_type: 'INTERVENTIONAL',
      intervention_types: ['DRUG'],
    },
    {
      nct_id: 'NCT04751981',
      brief_title: 'Elranatamab (PF-06863135) Anti-BCMA Bispecific Antibody in Multiple Myeloma — MagnetisMM-3',
      overall_status: 'NOT_YET_RECRUITING',
      phases: ['PHASE2'],
      conditions: ['Multiple Myeloma', 'Relapsed/Refractory Multiple Myeloma'],
      brief_summary: 'MagnetisMM-3 is an open-label, multicenter Phase 2 study of elranatamab, a humanized BCMA-CD3 bispecific antibody, in patients with relapsed or refractory multiple myeloma who have received at least three prior lines of therapy. New cohorts are opening at additional investigator sites across Europe and the Asia-Pacific region.',
      start_date: '2026-02-01',
      primary_completion_date: '2029-04-01',
      healthy_volunteers: false,
      minimum_age: '18 Years',
      maximum_age: null,
      nearest_facility: 'University Hospital Munich (LMU Klinikum)',
      nearest_city: 'Munich',
      nearest_state: 'Bavaria',
      nearest_country: 'Germany',
      nearest_distance_miles: null,
      nearest_lat: 48.1099,
      nearest_lon: 11.4716,
      investigators: [
        { name: 'Christian Straka, M.D.', role: 'PRINCIPAL_INVESTIGATOR', email: 'christian.straka@med.uni-muenchen.de', phone: '+49-89-4400-72210' },
      ],
      site_contacts: [],
      overall_contacts: [
        { name: 'Pfizer Medical Information', role: 'CONTACT', email: 'ClinicalTrials.gov_Inquiries@pfizer.com', phone: '1-800-718-1021' },
      ],
      total_sites: 28,
      countries_at_sites: ['Germany', 'France', 'Spain', 'Italy', 'Netherlands', 'Australia', 'Japan'],
      sponsor_type: 'INDUSTRY',
      study_type: 'INTERVENTIONAL',
      intervention_types: ['BIOLOGICAL'],
    },
    {
      nct_id: 'NCT05159388',
      brief_title: 'Biomarker Repository and Longitudinal Outcomes in Newly Diagnosed Multiple Myeloma (BIOLOMM)',
      overall_status: 'RECRUITING',
      phases: [],
      conditions: ['Multiple Myeloma', 'Newly Diagnosed Multiple Myeloma', 'Smoldering Myeloma'],
      brief_summary: 'BIOLOMM is a prospective, longitudinal observational study collecting serial biospecimens (blood, bone marrow, and tissue) from patients with newly diagnosed or smoldering multiple myeloma. The study aims to identify genomic, proteomic, and immunologic predictors of disease progression and treatment response. Open to healthy volunteers for control cohort.',
      start_date: '2022-01-15',
      primary_completion_date: '2030-01-01',
      healthy_volunteers: true,
      minimum_age: '18 Years',
      maximum_age: null,
      nearest_facility: 'The Royal Melbourne Hospital',
      nearest_city: 'Melbourne',
      nearest_state: 'Victoria',
      nearest_country: 'Australia',
      nearest_distance_miles: null,
      nearest_lat: -37.7993,
      nearest_lon: 144.955,
      investigators: [
        { name: 'Andrew Spencer, M.D.', role: 'PRINCIPAL_INVESTIGATOR', email: 'aspencer@alfred.org.au', phone: '+61-3-9076-3393' },
        { name: 'H. Miles Prince, M.D.', role: 'SUB_INVESTIGATOR', email: null, phone: null },
      ],
      site_contacts: [
        { name: 'Myeloma Research Group', role: 'CONTACT', email: 'myeloma.research@alfred.org.au', phone: '+61-3-9076-2000' },
      ],
      overall_contacts: [],
      total_sites: 14,
      countries_at_sites: ['Australia', 'New Zealand', 'United Kingdom', 'United States'],
      sponsor_type: 'OTH',
      study_type: 'OBSERVATIONAL',
      intervention_types: [],
    },
    {
      nct_id: 'NCT05617248',
      brief_title: 'GPRC5D × CD3 Bispecific Antibody Talquetamab in Combination With Daratumumab in Triple-Class Refractory Myeloma',
      overall_status: 'NOT_YET_RECRUITING',
      phases: ['EARLY_PHASE1'],
      conditions: ['Relapsed/Refractory Multiple Myeloma', 'Triple-Class Refractory Multiple Myeloma'],
      brief_summary: 'A Phase 1 dose-escalation study of talquetamab, a GPRC5D-CD3 bispecific antibody, combined with daratumumab SC in patients with triple-class refractory multiple myeloma (refractory to a proteasome inhibitor, an IMiD, and an anti-CD38 antibody). Primary objectives are safety, tolerability, and recommended Phase 2 dose.',
      start_date: '2026-05-01',
      primary_completion_date: '2028-11-01',
      healthy_volunteers: false,
      minimum_age: '18 Years',
      maximum_age: null,
      nearest_facility: 'National Cancer Center Hospital',
      nearest_city: 'Tokyo',
      nearest_state: null,
      nearest_country: 'Japan',
      nearest_distance_miles: null,
      nearest_lat: 35.6651,
      nearest_lon: 139.7314,
      investigators: [
        { name: 'Kenshi Suzuki, M.D.', role: 'PRINCIPAL_INVESTIGATOR', email: 'k-suzuki@jfcr.or.jp', phone: '+81-3-3520-0111' },
      ],
      site_contacts: [],
      overall_contacts: [
        { name: 'Janssen Medical Affairs', role: 'CONTACT', email: 'JNJ.CT@sylogent.com', phone: '1-877-594-1300' },
      ],
      total_sites: 12,
      countries_at_sites: ['Japan', 'South Korea', 'Taiwan', 'United States'],
      sponsor_type: 'INDUSTRY',
      study_type: 'INTERVENTIONAL',
      intervention_types: ['BIOLOGICAL'],
    },
  ],
}
